/* Auto-generated by decode_gameassets.py - soldier data from Soldier.txt. */
/* !!UNVALIDATED LAYOUT!! Field offsets below are GUESSED, not IL2CPP-verified.
   Do NOT use struct fields to drive packet sends until each offset is validated
   against a known in-game value. Only the tier grouping (u16@26, 1..7) is
   structurally confirmed. See lords-bot-data-tables-layout-caveat.md */
#pragma once
#include <stdint.h>
#define GAME_SOLDIER_N 37
typedef struct { uint16_t id; uint16_t tier; uint16_t unk6; uint16_t unk8;
                  uint32_t food; uint16_t load; } GameSoldier;
static const GameSoldier kGameSoldiers[37] = {
    { 1, 1, 39, 0, 2294018u, 1 },
    { 2, 1, 39, 0, 2294280u, 1 },
    { 3, 1, 39, 0, 2294552u, 1 },
    { 4, 1, 39, 0, 2294820u, 1 },
    { 5, 2, 39, 0, 2294018u, 2 },
    { 6, 2, 39, 0, 2294280u, 2 },
    { 7, 2, 39, 0, 2294552u, 2 },
    { 8, 2, 39, 0, 2294820u, 2 },
    { 9, 3, 39, 0, 2294018u, 3 },
    { 10, 3, 39, 0, 2294280u, 3 },
    { 11, 3, 39, 0, 2294552u, 3 },
    { 12, 3, 40, 0, 2294820u, 3 },
    { 13, 4, 40, 0, 3277058u, 4 },
    { 14, 4, 40, 0, 3277320u, 4 },
    { 15, 4, 40, 0, 3277592u, 4 },
    { 16, 4, 40, 0, 3277860u, 4 },
    { 17, 5, 40, 0, 2u, 5 },
    { 18, 5, 40, 0, 3u, 5 },
    { 19, 5, 40, 0, 4u, 5 },
    { 20, 5, 40, 0, 5u, 5 },
    { 21, 6, 40, 0, 2u, 6 },
    { 22, 6, 40, 0, 3u, 6 },
    { 23, 6, 40, 0, 4u, 6 },
    { 24, 6, 40, 0, 5u, 6 },
    { 25, 7, 40, 0, 2u, 7 },
    { 26, 7, 40, 0, 3u, 7 },
    { 27, 7, 40, 0, 4u, 7 },
    { 28, 7, 40, 0, 5u, 7 },
    { 29, 0, 0, 0, 0u, 0 },
    { 30, 0, 0, 0, 0u, 0 },
    { 31, 0, 0, 0, 0u, 0 },
    { 32, 0, 0, 0, 0u, 0 },
    { 33, 0, 0, 0, 0u, 0 },
    { 34, 1, 297, 0, 2295088u, 1 },
    { 35, 2, 297, 0, 2295088u, 2 },
    { 36, 3, 297, 0, 2295088u, 3 },
    { 37, 4, 297, 0, 3278128u, 4 },
};
static inline const GameSoldier* game_soldier_get(uint16_t id){
    int lo=0, hi=GAME_SOLDIER_N-1, idx=-1;
    while(lo<=hi){ int mid=(lo+hi)/2; const GameSoldier*x=&kGameSoldiers[mid];
        if(x->id<id) lo=mid+1; else { idx=mid; hi=mid-1; } }
    if(idx<0) return NULL;
    const GameSoldier*x=&kGameSoldiers[idx];
    return (x->id==id)?x:0;
}
